export const HISTORY_PHOTOS = {
  gallery: [
    "/history/cup-gallery-01.jpg",
    "/history/cup-gallery-02.jpg",
    "/history/cup-gallery-03.jpg",
    "/history/cup-gallery-04.jpg",
  ],
  coaches: {
    "Ahmed Samy": "/history/coach-ahmed-samy.jpg",
    "Emad El-Nahhas": "/history/coach-emad-el-nahhas.jpg",
    "Nabil Kouki": "/history/coach-nabil-kouki.jpeg",
    "Anis Boujelbene": "/history/coach-anis-boujelbene.jpeg",
    "Mimi Abdelrazek": "/history/coach-mimi-abdelrazek.jpeg",
    "Ali Maher": null,
    "Mahmoud Abou-Regaila": "/history/coach-mahmoud-abou-regaila.jpg",
    "Mohsen Saleh": "/history/coach-mohsen-saleh.jpeg",
    "Wojciech Lazarek": "/history/coach-wojciech-lazarek.jpg",
    "Farouk Gaafar": "/history/coach-farouk-gaafar.jpg",
    "Taha Basry": "/history/coach-taha-basry.jpg",
    "Tarek Yehia": "/history/coach-tarek-yehia.jpg",
    "Oscar Fulloné": "/history/coach-oscar-fullone.jpg",
    "Tarek Soliman": "/history/coach-tarek-soliman.jpeg",
    "Mohamed Helmi": "/history/coach-mohamed-helmi.jpeg",
    "Talaat Youssef": "/history/coach-talaat-youssef.jpeg",
    "Mokhtar Mokhtar": "/history/coach-mokhtar-mokhtar.jpeg",
    "Mostafa Younes": "/history/coach-mostafa-younes.jpeg",
  },
  presidents: {
    "السيد متولي": "/history/pres-sayed-metwally.jpeg",
    "كامل أبو علي": "/history/pres-kamel-abo-ali.jpeg",
    "علي فرج الله": "/history/pres-ali-farag-allah.jpg",
    "عبد الوهاب قوطة": "/history/pres-abdelwahab-kota.jpeg",
    "ياسر يحيى": "/history/pres-yasser-yehia.jpg",
    "سمير حلبية": "/history/pres-samir-halabia.jpg",
    "عبد الرحمن باشا لطفي": "/history/pres-abdelrahman-lotfy.jpeg",
  },
  players: {
    "Amr Moussa": null,
    "Karim El Eraki": null,
    "Farid Shawky": null,
    "Hassan Ali": null,
    "Osama Azab": null,
    "Ahmed Gomaa": "/history/record-ahmed-gomaa.jpeg",
    "Mohamed Grendo": "/history/record-mohamed-grendo.jpeg",
    "Ahmed Masoud": null,
    "Ashour El Adham": null,
    "Ahmed Shedid Kenawi": null,
    "Emeka Christian Eze": null,
    "Amr El Saadawy": null,
    "Islam Salah": null,
    "Austin Amutu": "/history/record-austin-amutu.jpeg",
    "Ahmed Fawzy": null,
    "Abderrahim Deghmoum": null,
    "Mahmoud Hamada": null,
    "Ahmed Ayman Mansour": null,
    "Ahmed Yasser": null,
    "Ahmed Shousha": null,
  },
  scorers: {
    "السيد الضظوي": "/history/record-sayed-eldazwy.jpg",
    "مسعد نور": "/history/record-mosaad-nour.jpeg",
    "محمد شاهين": "/history/record-mohamed-shahin.jpg",
    "جمال جودة": "/history/record-gamal-gouda.jpeg",
    "محمد بدوي": "/history/record-mohamed-badawy.jpg",
    "أحمد جمعة": "/history/record-ahmed-gomaa.jpeg",
    "إبراهيم المصري": "/history/record-ibrahim-elmasry.jpeg",
    "إينو": "/history/record-eno.jpeg",
  },
  legends: {
    "السيد الضظوي": "/history/record-sayed-eldazwy.jpg",
    "مسعد نور «الكاستن»": "/history/record-mosaad-nour.jpeg",
    "عبد الرحمن فوزي": "/history/legend-abdelrahman-fawzi.jpeg",
    "محسن صالح": "/history/legend-mohsen-saleh.jpeg",
    "إبراهيم المصري «مارادونا بورسعيد»": "/history/record-ibrahim-elmasry.jpeg",
    "محمد شاهين": "/history/record-mohamed-shahin.jpg",
    "إينو": "/history/record-eno.jpeg",
  },
} as const;